# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(779, 614)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setStyleSheet("background-color: #393E46;\n"
"border-radius:8px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setStyleSheet("background-color: #393E46;\n"
"border-radius:8px;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.widget_3)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"        border: 0px;\n"
"        background: transparent;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background: rgb(94, 111, 136);\n"
"        color: white;\n"
"        padding: 8px;\n"
"        border-radius:8px;\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background: rgb(34, 40, 49);\n"
"    }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_5 = QtWidgets.QWidget(parent=self.tab)
        self.widget_5.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.start_agent = QtWidgets.QPushButton(parent=self.widget_5)
        self.start_agent.setMinimumSize(QtCore.QSize(0, 30))
        self.start_agent.setStyleSheet("\n"
"  QPushButton {\n"
"                background-color: rgb(94, 111, 136);\n"
"                    color:rgb(255, 255, 255);\n"
"            }\n"
"\n"
"\n"
"  QPushButton:hover {\n"
"                background-color: rgb(57, 62, 70);\n"
"            }\n"
"")
        self.start_agent.setObjectName("start_agent")
        self.verticalLayout_13.addWidget(self.start_agent)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_15 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_15.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_15.setStyleSheet("background-color: rgb(94, 111, 136);")
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_4.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_16.setStyleSheet("background-color: rgb(94, 111, 136);")
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_4.addWidget(self.widget_16)
        self.verticalLayout_13.addWidget(self.widget_2)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_6 = QtWidgets.QWidget(parent=self.tab_2)
        self.widget_6.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_9)
        self.widget_11.setStyleSheet("background-color: rgb(94, 111, 136);")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_11)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.widget_14 = QtWidgets.QWidget(parent=self.widget_13)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_date = QtWidgets.QLineEdit(parent=self.widget_14)
        self.user_date.setMinimumSize(QtCore.QSize(0, 35))
        self.user_date.setMaximumSize(QtCore.QSize(16777215, 35))
        self.user_date.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.user_date.setObjectName("user_date")
        self.horizontalLayout_3.addWidget(self.user_date)
        self.user_hour = QtWidgets.QLineEdit(parent=self.widget_14)
        self.user_hour.setMinimumSize(QtCore.QSize(0, 35))
        self.user_hour.setMaximumSize(QtCore.QSize(16777215, 35))
        self.user_hour.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.user_hour.setObjectName("user_hour")
        self.horizontalLayout_3.addWidget(self.user_hour)
        self.verticalLayout_10.addWidget(self.widget_14)
        self.verticalLayout_11.addWidget(self.widget_13)
        self.now_btn = QtWidgets.QPushButton(parent=self.widget_11)
        self.now_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.now_btn.setStyleSheet("\n"
"  QPushButton {\n"
"                background-color: rgb(34, 40, 49);\n"
"                    color:rgb(255, 255, 255);\n"
"            }\n"
"\n"
"\n"
"  QPushButton:hover {\n"
"                background-color: rgb(57, 62, 70);\n"
"            }\n"
"")
        self.now_btn.setObjectName("now_btn")
        self.verticalLayout_11.addWidget(self.now_btn)
        self.verticalLayout_12.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(parent=self.widget_9)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_12.addWidget(self.widget_12)
        self.horizontalLayout_2.addWidget(self.widget_9, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.daily_notices = QtWidgets.QTextEdit(parent=self.widget_10)
        self.daily_notices.setStyleSheet("QTextEdit {\n"
"        background-color: #FFF8F8;\n"
"        color: rgb(0, 0, 0);\n"
"        font-size: 14px;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #f0f0f0;\n"
"        width: 12px;\n"
"        margin: 5px 0 5px 0;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #c4c4c4;\n"
"        min-height: 30px;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical:hover {\n"
"        background: #a0a0a0;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical,\n"
"    QScrollBar::sub-line:vertical {\n"
"        height: 0px;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical,\n"
"    QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }")
        self.daily_notices.setObjectName("daily_notices")
        self.verticalLayout_8.addWidget(self.daily_notices)
        self.horizontalLayout_2.addWidget(self.widget_10)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(parent=self.page)
        self.widget_4.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(parent=self.widget_7)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.sys_template = QtWidgets.QTextEdit(parent=self.widget_7)
        self.sys_template.setStyleSheet("QTextEdit {\n"
"        background-color: #FFF8F8;\n"
"        color: rgb(0, 0, 0);\n"
"        font-size: 14px;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #f0f0f0;\n"
"        width: 12px;\n"
"        margin: 5px 0 5px 0;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #c4c4c4;\n"
"        min-height: 30px;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical:hover {\n"
"        background: #a0a0a0;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical,\n"
"    QScrollBar::sub-line:vertical {\n"
"        height: 0px;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical,\n"
"    QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }")
        self.sys_template.setObjectName("sys_template")
        self.verticalLayout_7.addWidget(self.sys_template)
        self.horizontalLayout.addWidget(self.widget_7)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.tabWidget.addTab(self.page, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_17 = QtWidgets.QWidget(parent=self.tab_3)
        self.widget_17.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_18 = QtWidgets.QWidget(parent=self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_14.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_19 = QtWidgets.QWidget(parent=self.widget_18)
        self.widget_19.setStyleSheet("background-color: rgb(94, 111, 136);")
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_20 = QtWidgets.QWidget(parent=self.widget_19)
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_20)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_16.addWidget(self.label_6)
        self.widget_24 = QtWidgets.QWidget(parent=self.widget_20)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_24)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_20.addWidget(self.label_7)
        self.tool_name = QtWidgets.QLineEdit(parent=self.widget_24)
        self.tool_name.setMinimumSize(QtCore.QSize(0, 35))
        self.tool_name.setMaximumSize(QtCore.QSize(16777215, 35))
        self.tool_name.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.tool_name.setObjectName("tool_name")
        self.verticalLayout_20.addWidget(self.tool_name)
        self.verticalLayout_16.addWidget(self.widget_24)
        self.widget_25 = QtWidgets.QWidget(parent=self.widget_20)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_25)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_21.addWidget(self.label_8)
        self.tool_description = QtWidgets.QTextEdit(parent=self.widget_25)
        self.tool_description.setStyleSheet("QTextEdit {\n"
"        background-color: #FFF8F8;\n"
"        color: rgb(0, 0, 0);\n"
"        font-size: 14px;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #f0f0f0;\n"
"        width: 12px;\n"
"        margin: 5px 0 5px 0;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #c4c4c4;\n"
"        min-height: 30px;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical:hover {\n"
"        background: #a0a0a0;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical,\n"
"    QScrollBar::sub-line:vertical {\n"
"        height: 0px;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical,\n"
"    QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }")
        self.tool_description.setObjectName("tool_description")
        self.verticalLayout_21.addWidget(self.tool_description)
        self.verticalLayout_16.addWidget(self.widget_25)
        self.widget_26 = QtWidgets.QWidget(parent=self.widget_20)
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_26)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_22.addWidget(self.label_9)
        self.tool_path = QtWidgets.QLineEdit(parent=self.widget_26)
        self.tool_path.setMinimumSize(QtCore.QSize(0, 35))
        self.tool_path.setMaximumSize(QtCore.QSize(16777215, 35))
        self.tool_path.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.tool_path.setObjectName("tool_path")
        self.verticalLayout_22.addWidget(self.tool_path)
        self.verticalLayout_16.addWidget(self.widget_26)
        self.widget_27 = QtWidgets.QWidget(parent=self.widget_20)
        self.widget_27.setObjectName("widget_27")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_27)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_23.addWidget(self.label_10)
        self.tool_interpreter = QtWidgets.QLineEdit(parent=self.widget_27)
        self.tool_interpreter.setMinimumSize(QtCore.QSize(0, 35))
        self.tool_interpreter.setMaximumSize(QtCore.QSize(16777215, 35))
        self.tool_interpreter.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.tool_interpreter.setObjectName("tool_interpreter")
        self.verticalLayout_23.addWidget(self.tool_interpreter)
        self.verticalLayout_16.addWidget(self.widget_27)
        self.widget_21 = QtWidgets.QWidget(parent=self.widget_20)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_16.addWidget(self.widget_21)
        self.verticalLayout_15.addWidget(self.widget_20)
        self.include_btn = QtWidgets.QPushButton(parent=self.widget_19)
        self.include_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.include_btn.setStyleSheet("\n"
"  QPushButton {\n"
"                background-color: rgb(34, 40, 49);\n"
"                    color:rgb(255, 255, 255);\n"
"            }\n"
"\n"
"\n"
"  QPushButton:hover {\n"
"                background-color: rgb(57, 62, 70);\n"
"            }\n"
"")
        self.include_btn.setObjectName("include_btn")
        self.verticalLayout_15.addWidget(self.include_btn)
        self.verticalLayout_14.addWidget(self.widget_19)
        self.horizontalLayout_5.addWidget(self.widget_18, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_23 = QtWidgets.QWidget(parent=self.widget_17)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_18.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_23)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_18.addWidget(self.label_3)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget_23)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 520))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_18.addWidget(self.scrollArea)
        self.horizontalLayout_5.addWidget(self.widget_23)
        self.verticalLayout_19.addWidget(self.widget_17)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_agent.setText(_translate("Form", "INICIAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "WhatsApp"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">RESPONDER A PARTIR DE:</span></p></body></html>"))
        self.now_btn.setText(_translate("Form", "AGORA"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">AVISOS DO DIA</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Chat Config"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">TEMPLATE</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.page), _translate("Form", "AI Config"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">TOOLS </span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">NAME</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">DESCRIPTION</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">PYTHON PATH</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">INTERPRETER</span></p></body></html>"))
        self.include_btn.setText(_translate("Form", "INCLUDE"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">ACTIVE TOOLS</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Tools"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Charts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
