# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(779, 584)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setStyleSheet("background-color: #393E46;\n"
"border-radius:8px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setStyleSheet("background-color: #393E46;\n"
"border-radius:8px;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.widget_3)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"        border: 0px;\n"
"        background: transparent;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background: rgb(94, 111, 136);\n"
"        color: white;\n"
"        padding: 8px;\n"
"        border-radius:8px;\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background: rgb(34, 40, 49);\n"
"    }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_5 = QtWidgets.QWidget(parent=self.tab)
        self.widget_5.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.start_agent = QtWidgets.QPushButton(parent=self.widget_5)
        self.start_agent.setMinimumSize(QtCore.QSize(0, 30))
        self.start_agent.setStyleSheet("\n"
"  QPushButton {\n"
"                background-color: rgb(94, 111, 136);\n"
"                    color:rgb(255, 255, 255);\n"
"            }\n"
"\n"
"\n"
"  QPushButton:hover {\n"
"                background-color: rgb(57, 62, 70);\n"
"            }\n"
"")
        self.start_agent.setObjectName("start_agent")
        self.verticalLayout_13.addWidget(self.start_agent)
        self.live_chat = QtWidgets.QTextEdit(parent=self.widget_5)
        self.live_chat.setStyleSheet("QTextEdit {\n"
"        background-color: #FFF8F8;\n"
"        color: rgb(0, 0, 0);\n"
"        font-size: 14px;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #f0f0f0;\n"
"        width: 12px;\n"
"        margin: 5px 0 5px 0;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #c4c4c4;\n"
"        min-height: 30px;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical:hover {\n"
"        background: #a0a0a0;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical,\n"
"    QScrollBar::sub-line:vertical {\n"
"        height: 0px;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical,\n"
"    QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }")
        self.live_chat.setObjectName("live_chat")
        self.verticalLayout_13.addWidget(self.live_chat)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_6 = QtWidgets.QWidget(parent=self.tab_2)
        self.widget_6.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_9)
        self.widget_11.setStyleSheet("background-color: rgb(94, 111, 136);")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_11)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_13)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.widget_14 = QtWidgets.QWidget(parent=self.widget_13)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_date = QtWidgets.QLineEdit(parent=self.widget_14)
        self.user_date.setMinimumSize(QtCore.QSize(0, 35))
        self.user_date.setMaximumSize(QtCore.QSize(16777215, 35))
        self.user_date.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.user_date.setObjectName("user_date")
        self.horizontalLayout_3.addWidget(self.user_date)
        self.user_hour = QtWidgets.QLineEdit(parent=self.widget_14)
        self.user_hour.setMinimumSize(QtCore.QSize(0, 35))
        self.user_hour.setMaximumSize(QtCore.QSize(16777215, 35))
        self.user_hour.setStyleSheet("background-color: #FFF8F8;\n"
"color: rgb(34, 40, 49);\n"
" padding: 5px;\n"
"")
        self.user_hour.setObjectName("user_hour")
        self.horizontalLayout_3.addWidget(self.user_hour)
        self.verticalLayout_10.addWidget(self.widget_14)
        self.verticalLayout_11.addWidget(self.widget_13)
        self.now_btn = QtWidgets.QPushButton(parent=self.widget_11)
        self.now_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.now_btn.setStyleSheet("\n"
"  QPushButton {\n"
"                background-color: rgb(34, 40, 49);\n"
"                    color:rgb(255, 255, 255);\n"
"            }\n"
"\n"
"\n"
"  QPushButton:hover {\n"
"                background-color: rgb(57, 62, 70);\n"
"            }\n"
"")
        self.now_btn.setObjectName("now_btn")
        self.verticalLayout_11.addWidget(self.now_btn)
        self.verticalLayout_12.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(parent=self.widget_9)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_12.addWidget(self.widget_12)
        self.horizontalLayout_2.addWidget(self.widget_9, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.daily_notices = QtWidgets.QTextEdit(parent=self.widget_10)
        self.daily_notices.setStyleSheet("QTextEdit {\n"
"        background-color: #FFF8F8;\n"
"        color: rgb(0, 0, 0);\n"
"        font-size: 14px;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #f0f0f0;\n"
"        width: 12px;\n"
"        margin: 5px 0 5px 0;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #c4c4c4;\n"
"        min-height: 30px;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical:hover {\n"
"        background: #a0a0a0;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical,\n"
"    QScrollBar::sub-line:vertical {\n"
"        height: 0px;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical,\n"
"    QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }")
        self.daily_notices.setObjectName("daily_notices")
        self.verticalLayout_8.addWidget(self.daily_notices)
        self.horizontalLayout_2.addWidget(self.widget_10)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(parent=self.page)
        self.widget_4.setStyleSheet("background-color: #222831;\n"
"border-radius:8px;")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(parent=self.widget_7)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.sys_template = QtWidgets.QTextEdit(parent=self.widget_7)
        self.sys_template.setStyleSheet("QTextEdit {\n"
"        background-color: #FFF8F8;\n"
"        color: rgb(0, 0, 0);\n"
"        font-size: 14px;\n"
"        padding: 5px;\n"
"    }\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #f0f0f0;\n"
"        width: 12px;\n"
"        margin: 5px 0 5px 0;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #c4c4c4;\n"
"        min-height: 30px;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical:hover {\n"
"        background: #a0a0a0;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical,\n"
"    QScrollBar::sub-line:vertical {\n"
"        height: 0px;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical,\n"
"    QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }")
        self.sys_template.setObjectName("sys_template")
        self.verticalLayout_7.addWidget(self.sys_template)
        self.horizontalLayout.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout.addWidget(self.widget_8)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.tabWidget.addTab(self.page, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_agent.setText(_translate("Form", "COMEÇAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "WhatsApp"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">RESPONDER A PARTIR DE:</span></p></body></html>"))
        self.now_btn.setText(_translate("Form", "AGORA"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">AVISOS DO DIA</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Chat Config"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">TEMPLATE</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.page), _translate("Form", "AI Config"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
